import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import Header from "@/components/header/Header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["100", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Solimania",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string | undefined };
}) {
  const locale = useLocale();

  console.log(locale);
  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={` ${locale === "en" ? inter.className : roboto.className}`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
